# Generated by Django 4.1 on 2022-12-22 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz_app.basemodel')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('quiz_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz_app.basemodel')),
                ('asking', models.CharField(max_length=264)),
                ('marks', models.IntegerField(default=5)),
                ('of_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='quiz_app.category')),
            ],
            bases=('quiz_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz_app.basemodel')),
                ('option', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('of_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz_app.question')),
            ],
            bases=('quiz_app.basemodel',),
        ),
    ]
