# Generated by Django 4.1 on 2023-02-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asking',
            field=models.CharField(max_length=264),
        ),
    ]
