# Generated by Django 4.1 on 2022-12-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_answer_created_at_alter_answer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
