# Generated by Django 4.1 on 2022-12-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_rename_created_at_answer_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
