# Generated by Django 4.1 on 2023-02-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
