# Generated by Django 4.1 on 2023-02-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_delete_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
