# Generated by Django 4.1 on 2023-02-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0003_remove_article_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscussionForum',
        ),
    ]
