# Generated by Django 4.1 on 2023-02-19 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discussion_forum_app.basemodel')),
                ('asking', models.CharField(max_length=264)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_question', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('discussion_forum_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discussion_forum_app.basemodel')),
                ('statement', models.TextField()),
                ('answer_to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='discussion_forum_app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('discussion_forum_app.basemodel',),
        ),
    ]
