# Generated by Django 4.1 on 2023-02-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_userprofile_status_userprofile_is_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='images/profilepics'),
        ),
    ]
